baseURL: "https://xiongguisheng.com/"
languageCode: "en-us"
title: "Gus's Blog"
googleAnalytics: ""
disqusShortname: "gus"
ignoreFiles: [
  "\\.Rmarkdown$", "\\.Rmd$", "\\.knit\\.md$", "\\.utf8\\.md$",
  "_files$", "_cache$", "\\.txt$", "\\.csv$", "\\.tsv$",
  "\\.tgz$", "\\.tar$", "\\.gz$", "\\.zip$", "\\.npz$"]
hasCJKLanguage: true
enableEmoji: true
rssLimit: 100

permalinks:
  article: "/article/:slug/"

menu:
  home:
    - name: "Article"
      url: "/article/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Article"
      url: "/article/"
      weight: 2
    - name: "About"
      url: "/about/"
      weight: 3
  article:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Article"
      url: "/article/"
      weight: 2
    - name: "Categories"
      url: "/categories/"
      weight: 3
    - name: "About"
      url: "/about/"
      weight: 4
    
taxonomies:
  category: categories

params:
  description: "Gus's Personal Website | 熊桂生的个人网站"
  footer: "Copyright &copy; 2023-{Year} [xiongguisheng.com](/)"
  disqusURL: "https://xiongguisheng.com"
  licenseURL: "https://github.com/xiongus/xiongguisheng.com/blob/main/LICENSE"
  googleAdsense: ""

  jsCookieVersion: "3.0.0"
  jsCookieCDN: "//cdnjs.cloudflare.com/ajax/libs"

  clipboardjsVersion: "2.0.11"
  clipboardjsCDN: "//cdnjs.cloudflare.com/ajax/libs"

  prismjsVersion: "1.29.0"
  prismjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  prismjsPluginJS: ["autoloader", "show-language", "toolbar"]
  prismjsPluginCSS: ["toolbar"]

  mathjaxVersion: "3.2.2"
  mathjaxCDN: "//cdnjs.cloudflare.com/ajax/libs"

  pseudocodeVersion: "latest"
  pseudocodeCDN: "//cdn.jsdelivr.net/npm"

  jQueryVersion: "3.6.3"
  jQueryCDN: "//cdnjs.cloudflare.com/ajax/libs"

  photoswipeVersion: "4.1.3"
  photoswipeCDN: "//cdnjs.cloudflare.com/ajax/libs"

  videojsVersion: "8.0.3"
  videojsCDN: "//cdnjs.cloudflare.com/ajax/libs"

  materialComponentsWebVersion: "latest"
  materialComponentsWebCDN: "//cdn.jsdelivr.net/npm"

  APlayerVersion: "1.10.1"
  APlayerCDN: "//cdnjs.cloudflare.com/ajax/libs"

  MetingJSVersion: "latest"
  MetingJSCDN: "//cdn.jsdelivr.net/npm"

  lazysizesVersion: "5.3.2"
  lazysizesCDN: "//cdnjs.cloudflare.com/ajax/libs"

  vanillaBackToTopVersion: "latest"
  vanillaBackToTopCDN: "//cdn.jsdelivr.net/npm"

  nanogallery2Version: "3.0.5"
  nanogallery2CDN: "//cdnjs.cloudflare.com/ajax/libs"

  lang:
    slogan:
      en: ""
      cn: ""
    author:
      en: ""
      cn: ""
    license:
      cn: "版权"
      en: "License"
    subscribe:
      cn: "订阅"
      en: "Subscribe"
    categories:
      cn: "分类"
      en: "Categories"
    tags:
      cn: "标签"
      en: "Tags"
    wordcount:
      cn: "字数"
      en: "Word Count"
    prismjs_copy:
      cn: "复制"
      en: "Copy"
    prismjs_copy_success:
      cn: "已复制"
      en: "Copied"
    prismjs_copy_error:
      cn: "按 Ctrl+C 复制"
      en: "Press Ctrl+C to copy"
    donate:
      cn: "赞 赏"
      en: "DONATE"
    donate_slogan:
      cn: "「真诚赞赏，手留余香」"
      en: "「Donation Given, Fragrance in Hand」"
    donate_2_cny:
      cn: "2 元"
      en: "2 CNY"
    donate_5_cny:
      cn: "5 元"
      en: "5 CNY"
    donate_10_cny:
      cn: "10 元"
      en: "10 CNY"
    donate_50_cny:
      cn: "50 元"
      en: "50 CNY"
    donate_100_cny:
      cn: "100 元"
      en: "100 CNY"
    donate_custom_cny:
      cn: "任意金额"
      en: "CUSTOM"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1
